services:
  backend:
    image: krng19/myrepo-backend:1.0
    ports:
      - "3000:3000"
    container_name: myrepo-backend
    environment:
      - NODE_ENV=development

  frontend:
    image: krng19/myrepo-frontend:1.0
    ports:
      - "4200:4200"
    container_name: myrepo-frontend
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://backend:3000
